# rollout template configs
#fullnameOverride: ""
environment: sandbox
domain: templarfelix.com
# virtualService:
#   extraHosts:
#   - www.host1.com
#   - www.host2.com
#   extraGateways:
#   - g1
#   - g2

replicas: 3
revisionHistoryLimit: 10
version: 0.0.1
image:
  registry: docker.io
  repository: argoproj/rollouts-demo
  tag: yellow
  imagePullPolicy: Always
ports:
  http: 8080
health:
  enabled: true
  readinessInitialDelay: 60
  livenessInitialDelay: 30
  path: /
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
resources:
  {}
  ## If you intend to use the 'resources' uncomment the lines below and remove value '{}' from it
  # limits:
  #   cpu: 200m
  #   memory: 328Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
strategy:
  canary:
    analysis:
      templates:
        {}
        ## If you intend to use the 'templates' uncomment the lines below and remove value '{}' from it
        # - custom-AnalysisTemplate
    steps:
      - setWeight: 0
      - setCanaryScale:
          replicas: 1
      - pause: {}
      - setWeight: 10
      - setCanaryScale:
          weight: 10
      - pause:
          duration: "20m"
      - setWeight: 80
      - setCanaryScale:
          weight: 80
      - pause:
          duration: "20m"
      - setWeight: 100
      - setCanaryScale:
          weight: 100
      - pause:
          duration: "10m"
env: {}
  # - name: AWS_REGION
  #   value: us-east-1
  # - name: AWS_DEFAULT_REGION
  #   value: us-east-1

envFrom: {}
  # - configMapRef:
  #     name: special-config
  # - secretRef:
  #     name: special-config

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Specifies annotations for this service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
pod:
  # Specifies annotations for pods
  annotations: {}
istio:
  virtualService:
    customHeaders: {}

owner: foo
