apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "rollout-Canary.fullname" . }}-rules
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "rollout-Canary.fullname" . }}
    app.kubernetes.io/name: {{ include "rollout-Canary.fullname" . }}
    helm.sh/chart: {{ include "rollout-Canary.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  args:
  - name: service-name
    value: {{ include "rollout-Canary.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  - name: environment
    value: {{.Values.environment}}
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: len(result) == 0 || result[0] >= 0.99
    failureLimit: 3
    provider:
      prometheus:
        address: https://515464:eyJrIjoiZGYwNjRjOTM1OTQ5MmVkMzYwMTMyYzA0Nzk4NTVhODQ0M2NkMjM2YSIsIm4iOiJncmFmYW5hLWFnZW50LW9wZXJhdG9yLW1ldHJpY3MiLCJpZCI6MjgxMDQyfQ==@prometheus-prod-10-prod-us-central-0.grafana.net/api/prom
        query: |
          sum(irate(
            istio_requests_total{env="{{`{{args.environment}}`}}",destination_service=~"{{`{{args.service-name}}`}}",destination_version="canary",response_code!~"5.*"}[5m]
          )) / 
          sum(irate(
            istio_requests_total{env="{{`{{args.environment}}`}}",destination_service=~"{{`{{args.service-name}}`}}",destination_version="canary"}[5m]
          ))
  - name: stable-vs-canary-success-rate
    interval: 5m
    successCondition: len(result) == 0 || result[0] <= 0
    failureLimit: 3
    provider:
      prometheus:
        address: https://515464:eyJrIjoiZGYwNjRjOTM1OTQ5MmVkMzYwMTMyYzA0Nzk4NTVhODQ0M2NkMjM2YSIsIm4iOiJncmFmYW5hLWFnZW50LW9wZXJhdG9yLW1ldHJpY3MiLCJpZCI6MjgxMDQyfQ==@prometheus-prod-10-prod-us-central-0.grafana.net/api/prom
        query: |
          sum(irate(
            istio_requests_total{env="{{`{{args.environment}}`}}",destination_service=~"{{`{{args.service-name}}`}}",destination_version="canary",response_code!~"5.*"}[5m]
          )) / 
          sum(irate(
            istio_requests_total{env="{{`{{args.environment}}`}}",destination_service=~"{{`{{args.service-name}}`}}",destination_version="canary"}[5m]
          ))
          -
          sum(irate(
            istio_requests_total{env="{{`{{args.environment}}`}}",destination_service=~"{{`{{args.service-name}}`}}",destination_version="stable",response_code!~"5.*"}[5m]
          )) / 
          sum(irate(
            istio_requests_total{env="{{`{{args.environment}}`}}",destination_service=~"{{`{{args.service-name}}`}}",destination_version="stable"}[5m]
          ))

---
# This file contains AnalysisTemplates referenced by Rollouts and Experiments in the examples.
# Please apply this file first, before running any of the examples.

---
# This AnalysisTemplate will run a Kubernetes Job every 5 seconds that succeeds.
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: {{ include "rollout-Canary.fullname" . }}-pass
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "rollout-Canary.fullname" . }}
    app.kubernetes.io/name: {{ include "rollout-Canary.fullname" . }}
    helm.sh/chart: {{ include "rollout-Canary.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  metrics:
  - name: pass
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: alpine:3.8
                command: [sh, -c]
                args: [exit 0]
              restartPolicy: Never
          backoffLimit: 0
    count: 1
---
# This AnalysisTemplate will run a Kubernetes Job every 5 seconds, with a 50% chance of failure.
# When the number of accumulated failures exceeds failureLimit, it will cause the analysis run to
# fail, and subsequently cause the rollout or experiment to abort.
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: {{ include "rollout-Canary.fullname" . }}-random-fail
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "rollout-Canary.fullname" . }}
    app.kubernetes.io/name: {{ include "rollout-Canary.fullname" . }}
    helm.sh/chart: {{ include "rollout-Canary.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  metrics:
  - name: random-fail
    count: 2
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: alpine:3.8
                command: [sh, -c]
                args: [FLIP=$(($(($RANDOM%10))%2)) && exit $FLIP]
              restartPolicy: Never
          backoffLimit: 0