apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for charts.templarfelix.com/v1alpha1, Kind: RolloutDeployment
##
- apiGroups:
  - charts.templarfelix.com
  resources:
  - rolloutdeployments
  - rolloutdeployments/status
  - rolloutdeployments/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "argoproj.io"
  resources:
  - "analysistemplates"
  - "rollouts"
- verbs:
  - "*"
  apiGroups:
  - "cert-manager.io"
  resources:
  - "certificates"
- verbs:
  - "*"
  apiGroups:
  - "networking.istio.io"
  resources:
  - "destinationrules"
  - "gateways"
  - "virtualservices"

#+kubebuilder:scaffold:rules
