# permissions for end users to view rolloutdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rolloutdeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: rolloutdeployment-viewer-role
rules:
- apiGroups:
  - charts.templarfelix.com
  resources:
  - rolloutdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.templarfelix.com
  resources:
  - rolloutdeployments/status
  verbs:
  - get
