# permissions for end users to edit rollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollout-editor-role
rules:
- apiGroups:
  - charts.templarfelix.com
  resources:
  - rollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.templarfelix.com
  resources:
  - rollouts/status
  verbs:
  - get
