# permissions for end users to view rolloutdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rolloutdeployment-viewer-role
rules:
- apiGroups:
  - charts.templarfelix.com
  resources:
  - rolloutdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.templarfelix.com
  resources:
  - rolloutdeployments/status
  verbs:
  - get
