apiVersion: charts.templarfelix.com/v1alpha1
kind: Rollout
metadata:
  name: rollout-sample
spec:
  # Default values copied from <project_dir>/helm-charts/rollout/values.yaml
  domain: templarfelix.com
  env: {}
  envFrom: {}
  environment: sandbox
  health:
    enabled: true
    livenessInitialDelay: 30
    path: /
    readinessInitialDelay: 60
  hpa:
    enabled: false
    maxReplicas: 5
    minReplicas: 2
  image:
    imagePullPolicy: Always
    registry: docker.io
    repository: argoproj/rollouts-demo
    tag: yellow
  istio:
    virtualService:
      customHeaders: {}
  owner: foo
  pod:
    annotations: {}
  ports:
    http: 8080
  replicas: 3
  resources: {}
  revisionHistoryLimit: 10
  serviceAccount:
    annotations: {}
    create: true
    name: null
  strategy:
    canary:
      analysis:
        templates: {}
      steps:
      - setWeight: 0
      - setCanaryScale:
          replicas: 1
      - pause: {}
      - setWeight: 10
      - setCanaryScale:
          weight: 10
      - pause:
          duration: 20m
      - setWeight: 80
      - setCanaryScale:
          weight: 80
      - pause:
          duration: 20m
      - setWeight: 100
      - setCanaryScale:
          weight: 100
      - pause:
          duration: 10m
  version: 0.0.1
  
  
