apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollout-Canary.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations: {}
  labels:
    app: {{ include "rollout-Canary.fullname" . }}
    app.kubernetes.io/name: {{ include "rollout-Canary.fullname" . }}
    helm.sh/chart: {{ include "rollout-Canary.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    owner: {{ .Values.owner | required "owner attribute is required. E.g: owner: foo" }}
spec:
  ports:
  {{- if .Values.ports.grpc }}
  - name: grpc-{{ include "rollout-Canary.fullname" $ }}
    port: {{ .Values.ports.grpc }}
    targetPort: {{ .Values.ports.grpc }}
  {{ else }}
  - name: http-{{ include "rollout-Canary.fullname" $ }}
    port: {{ .Values.ports.http }}
    targetPort: {{ .Values.ports.http }}
  {{- end }}
  selector:
    app: {{ include "rollout-Canary.fullname" . }}
    app.kubernetes.io/name: {{ include "rollout-Canary.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  #type: LoadBalancer