
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "rollout-Canary.fullname" . }}-cert-staging
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: {{ include "rollout-Canary.fullname" . }}-cert-staging
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - '{{ .Values.domain }}'
  issuerRef:
    name: letsencrypt-staging-cluster
    kind: ClusterIssuer
    group: cert-manager.io
---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: {{ include "rollout-Canary.fullname" . }}-cert-prod
#  namespace: {{ .Release.Namespace | quote }}
#spec:
#  secretName: {{ include "rollout-Canary.fullname" . }}-cert-prod
#  duration: 2160h # 90d
#  renewBefore: 360h # 15d
#  isCA: false
#  privateKey:
#    algorithm: RSA
#    encoding: PKCS1
#    size: 2048
#  usages:
#    - server auth
#    - client auth
#  dnsNames:
#    - '{{ .Values.domain }}'
#  issuerRef:
#    name: letsencrypt-prod-cluster
#    kind: ClusterIssuer
#    group: cert-manager.io